### ISSUE TITLE
Error while expanding /RDPTools/classifier/build/classes/data.tgz

### ISSUE THREAD

**Issue by philge** [rdpstaff/RDPTools#16]
Error while expanding /RDPTools/classifier/build/classes/data.tgz
java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
        at org.apache.tools.tar.TarBuffer.readBlock(TarBuffer.java:253)
        at org.apache.tools.tar.TarBuffer.readRecord(TarBuffer.java:220)
        at org.apache.tools.tar.TarInputStream.read(TarInputStream.java:603)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at org.apache.tools.ant.taskdefs.Expand.extractFile(Expand.java:358)
        at org.apache.tools.ant.taskdefs.Untar.expandStream(Untar.java:163)
        at org.apache.tools.ant.taskdefs.Untar.expandFile(Untar.java:109)
        at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:148)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

Total time: 15 seconds
make: *** [classifier/dist/classifier.jar] Error 1

**Comment by caijian89** [comment]
I am also encountering this error, could you kind to tell me the solution you fix it? @mortonjt
