### ISSUE TITLE
Error testing RDPTools on Frogs

### ISSUE THREAD

**Issue by jzegarrav** [rdpstaff/RDPTools#25]
When i run:

root@raquel-X555LDB:/home/raquel/FROGS-master/test# bash test.sh /home/raquel/FROGS-master/ 2 4 /tmp/results

Frogs can't found RDPTools jar classes:

Step preprocess tum awu  5 17:42:20 PET 2018
Step clustering tum awu  5 17:43:36 PET 2018
Step remove_chimera tum awu  5 17:44:20 PET 2018
Step filters tum awu  5 17:45:57 PET 2018
Step affiliation_OTU tum awu  5 17:45:58 PET 2018
Exception in thread "main" java.lang.NoClassDefFoundError: edu/msu/cme/rdp/taxatree/interfaces/TreeVisitor
	at edu.msu.cme.rdp.classifier.cli.ClassifierMain.main(ClassifierMain.java:67)
Caused by: java.lang.ClassNotFoundException: edu.msu.cme.rdp.taxatree.interfaces.TreeVisitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/raquel/FROGS-master//app/affiliation_OTU.py", line 192, in process_rdp
    rdp_cmd.submit(log_file)
  File "/home/raquel/FROGS-master/lib/frogsUtils.py", line 140, in submit
    subprocess.check_output( self.get_cmd(), shell=True )
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'taskset -c 0 java -Xmx4g -jar /home/raquel/FROGS-master/libexec/classifier.jar classify -c 0.0 -t /home/raquel/FROGS-master//test/data/db.fasta.properties -o /tmp/results/1533509158.25_11883_1533509158.25_11883_04-filters.fasta_0.rdp /tmp/results/1533509158.25_11883_04-filters.fasta_0' returned non-zero exit status 1

Traceback (most recent call last):
  File "/home/raquel/FROGS-master//app/affiliation_OTU.py", line 370, in <module>
    Blast(args.reference, args.input_fasta, blast_out_list[0], args.nb_cpus).submit(log_blast_list[0])
  File "/home/raquel/FROGS-master/lib/frogsUtils.py", line 135, in submit
    FH_log.write( '# ' + self.description + ' (' + os.path.basename(self.program) + ' version : ' + self.get_version() + ')\n' )
  File "/home/raquel/FROGS-master//app/affiliation_OTU.py", line 75, in get_version
    return Cmd.get_version(self, 'stdout').split()[1].strip()
IndexError: list index out of range
Error in affiliation_OTU

--------------------------------
I copied all rdptools jars to libexec.

Help

**Comment by mariabernard** [comment]
Hi!

We (@oinizan and I) encountered same problem, yesterday.
To resolve it, their is 2 solutions:

- not copy classifier.jar in the <FROGS>/libexec directory, but simply link it in that folder. This way classifier.jar will find the RDPTools lib dir.
 - copy classifier.jar AND lib directory of RDPTools in the <FROGS>/libexec folder

To may point of view it's easier and "nicer" to do the link as RDPTools/lib dir is not part of FROGS.

Best Regards
