### ISSUE TITLE
classifier/dist/classifier.jar] Error 1

### ISSUE THREAD

**Issue by shawn-liu-cell** [rdpstaff/RDPTools#38]
Dear all
I have a problem in make
BUILD FAILED
/root/RDPTools/classifier/build.xml:50: java.net.SocketException: Resource temporarily unavailable
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:997)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851)
        at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:736)
        at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:652)
        at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:642)

Total time: 23 seconds
make: *** [Makefile:24: classifier/dist/classifier.jar] Error 1

**Comment by rdpstaffmsu** [comment]
The rdpstaff email account was recently reactivated so that I can give you the bad news:
Unfortunately, the RDP server has died and there are no plans to replace it. Funding will not be renewed, the staff have retired or moved to other positions, and the office is closed.
However, all may not be lost. There are command line alternatives to the web based tools.

The RDP Classifier is available as a stand-alone tool at https://sourceforge.net/projects/rdp-classifier/. It is written in Java and so will run on any computer that has Java installed. I have added specific tutorials for installing and using it at https://john-quensen.com/tutorials/install-the-stand-alone-rdp-classifier/ and https://john-quensen.com/tutorials/stand-alone-rdp-classifier-tutorial/.

The RDPTools are available on GitHub and as a Docker image. The Docker version is much easier to install. See installation instructions at https://john-quensen.com/tutorials/tutorial-1/ and https://jfq3.gitbook.io/rdptools-docker/rdptools-docker/readme. Some models for use with the Xander Assembler are available at https://github.com/rdpstaff/Xander_assembler/tree/master/gene_resource.

I have instructions for my own command line version of the FunGene pipeline at https://john-quensen.com/workshops/workshop-2/command-line-fungene-pipeline/. Models for use with the FinGene pipeline are available at https://github.com/rdpstaff/fungene_pipeline/tree/master/resources.
Unfortunately there is no current replacement for the FunGene website.

A surprising number of health related organizations still use SeqMatch to classify sequences, and I have added instructions for downloading a SeqMatch database and running it from the command line at https://john-quensen.com/tutorials/seqmatch/. However, SeqMatch preceded the RDP Classifier, a superior tool for classification, and the RDP Classifier database is more recent. Honestly, SOPs should be updated to use a classification method other than SeqMatch.

Some thoughts about classification databases:
The RDP Classifier's database is the only curated database for the classification of bacteria and archaea by 16S rRNA gene sequences. That is, it contains only validly named species (using Bergey's classification as of 2021), which in turn means that it contains only species that have been cultured. The database for bacterial and archaeal sequences was updated in 2020 and I just learned (July 2023) that Qiong Wang has nearly completed another update. Email me (address below) if you want to receive notice of its availability.
Sequencing environmental samples informs us that most bacteria and archaea have never been cultured and therefore are not in the RDP Classifier database. SILVA and GreenGenes do include species known only from sequencing but with many errors in the lineages. In particular, the SILVA species assignment is sometimes the species from which the microorganism was isolated, i.e. a plant or animal. The GTDB project (https://gtdb.ecogenomic.org/) is an attempt to establish a standardized microbial taxonomy based on genome phylogeny, and its nomenclature is being adopted by NCBI.
Other classifiers (sometimes a re-coding of the RDP Classifier) are available in the QIIME2, mothur, USEARCH and VSEARCH packages. Sequences formatted to use with these classifiers are available at https://docs.qiime2.org/2023.5/data-resources/ and https://www.drive5.com/usearch/manual/sintax_downloads.html. See https://forum.qiime2.org/t/how-to-train-a-gtdb-ssu-classifier-using-rescript/25725 for how to train a QIIME classifier using 16S rRNA gene sequences from GTDB.

I have tried to answer the most common questions I have received. If you have additional questions, just email me.

John Quensen
***@***.***




________________________________
From: shawn-liu-cell ***@***.***>
Sent: Thursday, July 13, 2023 2:21 PM
To: rdpstaff/RDPTools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rdpstaff/RDPTools] classifier/dist/classifier.jar] Error 1 (Issue #38)


Dear all
I have a problem in make
BUILD FAILED
/root/RDPTools/classifier/build.xml:50: java.net.SocketException: Resource temporarily unavailable
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:579)
at java.net.Socket.connect(Socket.java:528)
at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
at sun.net.www.http.HttpClient.(HttpClient.java:211)
at sun.net.www.http.HttpClient.New(HttpClient.java:308)
at sun.net.www.http.HttpClient.New(HttpClient.java:326)
at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:997)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851)
at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:736)
at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:652)
at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:642)

Total time: 23 seconds
make: *** [Makefile:24: classifier/dist/classifier.jar] Error 1
